# Generated by Django 4.2.2 on 2023-06-27 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0002_candidate_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='age',
        ),
    ]
